CREATE TABLE MOVIE_INMEM
    AS SELECT * FROM MOVIE;

CREATE TABLE RATING_INMEM
    AS SELECT * FROM RATING;

CREATE TABLE TAG_INMEM
    AS SELECT * FROM TAG;


ALTER TABLE MOVIE_INMEM
    INMEMORY
        MEMCOMPRESS FOR QUERY HIGH
        PRIORITY HIGH;

ALTER TABLE RATING_INMEM
    INMEMORY
        MEMCOMPRESS FOR QUERY HIGH
        PRIORITY HIGH;

ALTER TABLE TAG_INMEM
    INMEMORY
        MEMCOMPRESS FOR QUERY HIGH
        PRIORITY HIGH;


